ARG HADOOP_BASE=movielens-governance-hadoop:3.3.6
ARG PYTHON_BASE=python:3.12-slim
FROM ${HADOOP_BASE} AS hadoop
FROM ${PYTHON_BASE}
COPY --from=hadoop /opt/hadoop-3.3.6 /opt/hadoop-3.3.6
COPY --from=hadoop /usr/local/openjdk-11 /opt/java
COPY hadoop-conf/*.xml /opt/hadoop-3.3.6/etc/hadoop/
COPY requirements-worker.txt /tmp/requirements-worker.txt
RUN pip install --no-cache-dir -r /tmp/requirements-worker.txt
ENV JAVA_HOME=/opt/java \
    HADOOP_HOME=/opt/hadoop-3.3.6 \
    HADOOP_MAPRED_HOME=/opt/hadoop-3.3.6 \
    HADOOP_CONF_DIR=/opt/hadoop-3.3.6/etc/hadoop \
    PATH=/opt/java/bin:/opt/hadoop-3.3.6/bin:/usr/local/bin:/usr/bin:/bin \
    PYTHONUNBUFFERED=1
WORKDIR /work
ENTRYPOINT ["python", "-m", "governance.worker"]
