'use strict';
const byId=id=>document.getElementById(id);
const statusNames={QUEUED:'排队中',RUNNING:'计算中',RECOVERING:'恢复中',VALIDATING:'校验中',PUBLISHING:'发布中',PUBLISHED:'已正式发布',FAILED:'失败'};
let selected=null, selection=0, runPage=null, evidenceCursor=null, evidenceFilters=null, evidenceRequest=0, busy=false;
const history=new Map();
function text(tag,value,className){const n=document.createElement(tag);n.textContent=value??'—';if(className)n.className=className;return n;}
function showError(error){byId('error').textContent=error?.message||String(error);}
async function api(url,options){const r=await fetch(url,options);if(!r.ok){let detail;try{detail=(await r.json()).detail;}catch{detail=`请求失败 (${r.status})`;}throw new Error(typeof detail==='string'?detail:JSON.stringify(detail));}return r.json();}
function table(headers,rows){const t=document.createElement('table');const head=t.createTHead().insertRow();headers.forEach(h=>head.append(text('th',h)));const body=t.createTBody();rows.forEach(row=>{const tr=body.insertRow();row.forEach(v=>tr.append(text('td',v)));});return t;}
async function loadHistory(append=false){try{const page=await api('/api/runs?limit=50'+(append&&runPage?'&before='+runPage:''));if(!append)history.clear();page.items.forEach(r=>history.set(r.run_id,r));runPage=page.next_before;byId('more').hidden=!runPage;renderHistory();}catch(e){showError(e);}}
function renderHistory(){const list=byId('tasks');list.replaceChildren();for(const r of history.values()){const b=text('button',`${statusNames[r.status]||r.status}\n${r.run_id}`, 'task'+(r.run_id===selected?' selected':''));b.onclick=()=>selectRun(r.run_id);list.append(b);}if(!history.size)list.append(text('p','暂无任务。','muted'));for(const id of ['left','right']){const select=byId(id),old=select.value;select.replaceChildren();for(const r of history.values())if(r.status==='PUBLISHED'){const o=text('option',`${r.run_id}${r.publish_id===r.current_publish_id?' · 当前版本':''}`);o.value=r.run_id;select.append(o);}if([...select.options].some(o=>o.value===old))select.value=old;}}
async function selectRun(id){selected=id;const generation=++selection;evidenceCursor=null;evidenceFilters=null;byId('error').textContent='';byId('evidence').replaceChildren();byId('ask-answer').textContent='';byId('compare').replaceChildren();byId('evidence-more').hidden=true;for(const panel of ['result-panel','evidence-panel','ask-panel'])byId(panel).hidden=true;byId('analysis-panel').hidden=true;byId('analysis').replaceChildren();byId('retry').hidden=true;byId('jobs-panel').hidden=true;byId('identity').replaceChildren(text('p','正在读取任务…'));renderHistory();await refreshSelected(generation);}
async function refreshSelected(generation=selection){const id=selected;if(!id)return;try{const r=await api('/api/runs/'+encodeURIComponent(id));if(generation!==selection)return;byId('empty').hidden=true;byId('identity').replaceChildren(text('p',statusNames[r.status]||r.status,'badge '+(r.status==='PUBLISHED'?'ok':r.status==='FAILED'?'bad':'')),text('p',`任务：${id}`),text('p',`阶段：${r.stage}`),text('p',`输入：${r.input_version} · 规则：${r.rule_version} · 指标：${r.metric_version}`));if(r.error)byId('identity').append(text('pre',JSON.stringify(r.error,null,2)));byId('retry').hidden=r.status!=='FAILED';byId('jobs-panel').hidden=!r.attempts.length;byId('analysis-panel').hidden=!r.attempts.length;byId('jobs').replaceChildren();for(const a of r.attempts){byId('jobs').append(text('h3',`第 ${a.attempt_no} 次尝试 · ${a.status}`),table(['阶段','状态','作业 ID'],a.jobs.map(j=>[j.stage,j.status,j.job_id||'等待提交'])));}if(history.has(id)){history.set(id,{...history.get(id),status:r.status,stage:r.stage});renderHistory();}if(r.status==='PUBLISHED'&&byId('result-panel').hidden){const report=await api('/api/runs/'+encodeURIComponent(id)+'/report');if(generation!==selection)return;byId('publish').textContent=`任务 ${report.run_id} · 输出版本 ${report.output_data_version}`;const rows=[];for(const [name,phases] of Object.entries(report.scores||{}))for(const metric of Object.keys(phases.raw||{}))rows.push([name,metric,phases.raw[metric]??'不适用',phases.clean?.[metric]??'不适用']);byId('scores').replaceChildren(table(['数据表','质量维度','清洗前','清洗后'],rows));byId('changes').textContent=JSON.stringify({row_change:report.row_change,disposition:report.disposition,split:report.split},null,2);byId('limitations').textContent=JSON.stringify(report.limitations,null,2);byId('download').href='/api/runs/'+encodeURIComponent(id)+'/report/download';for(const panel of ['result-panel','evidence-panel','ask-panel'])byId(panel).hidden=false;}}catch(e){if(generation===selection)showError(e);}}
byId('submit').onclick=async()=>{if(busy)return;busy=true;byId('submit').disabled=true;const key=sessionStorage.getItem('ml-submit-key')||crypto.randomUUID();sessionStorage.setItem('ml-submit-key',key);try{const r=await api('/api/runs',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({rule_pack:'default'})});sessionStorage.removeItem('ml-submit-key');byId('submit-status').textContent=`已提交 ${r.run_id}`;await loadHistory();await selectRun(r.run_id);}catch(e){showError(e);}finally{busy=false;byId('submit').disabled=false;}};
byId('retry').onclick=async()=>{const id=selected;byId('retry').disabled=true;try{await api('/api/runs/'+encodeURIComponent(id)+'/retry',{method:'POST'});await selectRun(id);await loadHistory();}catch(e){showError(e);}finally{byId('retry').disabled=false;}};
async function evidence(append=false){const id=selected,generation=selection,request=++evidenceRequest;try{if(!append){evidenceFilters=new URLSearchParams({limit:'25'});for(const [field,key] of [['source-table','source_table'],['rule','rule_id'],['source-id','source_record_id'],['metric','metric']]){const v=byId(field).value.trim();if(v)evidenceFilters.set(key,v);}evidenceCursor=null;}const query=new URLSearchParams(evidenceFilters);if(append&&evidenceCursor)query.set('after',evidenceCursor);const page=await api('/api/runs/'+encodeURIComponent(id)+'/evidence?'+query);if(generation!==selection||request!==evidenceRequest)return;if(!append)byId('evidence').replaceChildren();for(const row of page.items){const article=document.createElement('article');article.append(text('strong',`${row.source_table} · ${row.rule_id} · ${row.action||row.metric||row.kind}`),text('p',`来源记录：${row.source_record_id}`),text('pre',JSON.stringify(row,null,2)));byId('evidence').append(article);}if(!page.items.length&&!append)byId('evidence').append(text('p','没有符合条件的依据。'));evidenceCursor=page.next_after;byId('evidence-more').hidden=!evidenceCursor;}catch(e){if(generation===selection)showError(e);}}
byId('find-evidence').onclick=()=>evidence();byId('evidence-more').onclick=()=>evidence(true);
byId('compare-button').onclick=async()=>{const generation=selection;try{const q=new URLSearchParams({left:byId('left').value,right:byId('right').value});if(!q.get('left')||!q.get('right'))throw new Error('请选择两个正式任务。');const r=await api('/api/comparisons?'+q);if(generation!==selection)return;byId('compare').replaceChildren(text('p',r.limitations),text('pre',JSON.stringify(r.versions,null,2)),table(['数据表','阶段','指标','左侧','右侧','差值'],r.scores.map(x=>[x.table,x.phase,x.metric,x.left??'不适用',x.right??'不适用',x.delta??'不可比较'])));}catch(e){showError(e);}};
byId('ask').onclick=async()=>{const id=selected,generation=selection,q=byId('question').value.trim();if(!q)return;byId('ask').disabled=true;try{const r=await api('/api/tasks/'+encodeURIComponent(id)+'/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q})});if(generation!==selection)return;byId('ask-answer').textContent=(r.answer||'')+(r.flagged?.length?'\n存在未通过校验的内容：'+r.flagged.join('、'):'');}catch(e){showError(e);}finally{byId('ask').disabled=false;}};
byId('refresh').onclick=()=>loadHistory();byId('more').onclick=()=>loadHistory(true);
setInterval(()=>{if(selected)refreshSelected();},5000);loadHistory();

for(const [button,endpoint] of [['history-analysis','history-analysis'],['performance','performance']])byId(button).onclick=async()=>{const generation=selection,id=selected;byId(button).disabled=true;try{const data=await api('/api/runs/'+encodeURIComponent(id)+'/'+endpoint);if(generation===selection)byId('analysis').replaceChildren(text('pre',JSON.stringify(data,null,2)));}catch(e){if(generation===selection)showError(e);}finally{byId(button).disabled=false;}};
